server:
  port : 9091

spring:
#  flyway:
#    baseline-on-migrate: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    url: "jdbc:postgresql://localhost/musicdb" #"jdbc:h2:mem:music"
    username: "postgres"
    password: "password"
#  h2.console:
#    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect #org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true